// <auto-generated />
using System;
using AptekaDiplom2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AptekaDiplom22.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AptekaDiplom2.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AptekaDiplom2.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Ленина, 10",
                            Name = "Аптека №1 Центральная",
                            Phone = "+79000000001",
                            WorkingHours = "08:00-22:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "пр. Мира, 25",
                            Name = "Аптека №2 Солнечная",
                            Phone = "+79000000002",
                            WorkingHours = "09:00-21:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Садовая, 7",
                            Name = "Аптека №3 Заречная",
                            Phone = "+79000000003",
                            WorkingHours = "08:00-20:00"
                        });
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngredient")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrescriptionRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveIngredient = "Ацетилсалициловая кислота",
                            Description = "Жаропонижающее и обезболивающее средство",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Bayer",
                            Name = "Аспирин",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            ActiveIngredient = "Метамизол натрия",
                            Description = "Обезболивающее средство",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Фармстандарт",
                            Name = "Анальгин",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            ActiveIngredient = "Аскорбиновая кислота",
                            Description = "Витаминный комплекс для иммунитета",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Evalar",
                            Name = "Витамин C",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            ActiveIngredient = "Парацетамол",
                            Description = "Жаропонижающее средство",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Фармстандарт",
                            Name = "Парацетамол",
                            Price = 60m
                        },
                        new
                        {
                            Id = 5,
                            ActiveIngredient = "Амоксициллин",
                            Description = "Антибиотик широкого спектра действия",
                            IsPrescriptionRequired = true,
                            Manufacturer = "Sandoz",
                            Name = "Амоксициллин",
                            Price = 220m
                        },
                        new
                        {
                            Id = 6,
                            ActiveIngredient = "Ибупрофен",
                            Description = "Противовоспалительное и обезболивающее средство",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Reckitt Benckiser",
                            Name = "Нурофен",
                            Price = 180m
                        },
                        new
                        {
                            Id = 7,
                            ActiveIngredient = "Омепразол",
                            Description = "Средство для лечения язвенной болезни и гастрита",
                            IsPrescriptionRequired = true,
                            Manufacturer = "Sandoz",
                            Name = "Омепразол",
                            Price = 130m
                        },
                        new
                        {
                            Id = 8,
                            ActiveIngredient = "Лоратадин",
                            Description = "Противоаллергическое средство",
                            IsPrescriptionRequired = false,
                            Manufacturer = "Evalar",
                            Name = "Лоратадин",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("ProductId", "PharmacyId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PharmacyId = 1,
                            ProductId = 1,
                            Quantity = 100,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            PharmacyId = 2,
                            ProductId = 1,
                            Quantity = 50,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            PharmacyId = 1,
                            ProductId = 2,
                            Quantity = 200,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            PharmacyId = 2,
                            ProductId = 3,
                            Quantity = 30,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            PharmacyId = 1,
                            ProductId = 4,
                            Quantity = 80,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 6,
                            PharmacyId = 3,
                            ProductId = 4,
                            Quantity = 60,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 7,
                            PharmacyId = 1,
                            ProductId = 5,
                            Quantity = 25,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 8,
                            PharmacyId = 2,
                            ProductId = 5,
                            Quantity = 10,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 9,
                            PharmacyId = 2,
                            ProductId = 6,
                            Quantity = 70,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 10,
                            PharmacyId = 3,
                            ProductId = 6,
                            Quantity = 40,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 11,
                            PharmacyId = 1,
                            ProductId = 7,
                            Quantity = 15,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 12,
                            PharmacyId = 3,
                            ProductId = 8,
                            Quantity = 55,
                            ReservedQuantity = 0
                        });
                });

            modelBuilder.Entity("AptekaDiplom2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@apteka.ru",
                            FullName = "Администратор",
                            PasswordHash = "$2a$11$0wAaiL2YzKzhuKZTQ4mYye5C6CW2/sFAJh8dCZAVUbm1bz3lkz4cu",
                            Phone = "+79990000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Order", b =>
                {
                    b.HasOne("AptekaDiplom2.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AptekaDiplom2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AptekaDiplom2.Models.OrderItem", b =>
                {
                    b.HasOne("AptekaDiplom2.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AptekaDiplom2.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Stock", b =>
                {
                    b.HasOne("AptekaDiplom2.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AptekaDiplom2.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AptekaDiplom2.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
